### ISSUE TITLE
Back Button Broken in Navigation Sample

### ISSUE THREAD

**Issue by MelbourneDeveloper** [xamarin/xamarin-forms-samples#171] opened 2017-02-07 23:19 UTC
The back button doesn't work for the sample app Navigation\MasterDetailPage . The Detail property is being set to a new NavigationPage every time the content is changed. Instead, PushAsync should be used to push back information on to the stack.  There are probably other sample apps where this is a problem. Someone should look through all the apps to make sure this isn't a problem in other cases. This is severe problem because people who download the samples will be wondering why the back button is not working.

I have reported the bug here in Bugzilla and have specified some code recommended to fix the problem:
https://bugzilla.xamarin.com/show_bug.cgi?id=52348

**Comment by davidbritch** [comment] 2018-03-13 14:40
Apologies for the delayed response to this issue. The sample is behaving as intended, and this issue has been addressed here: https://bugzilla.xamarin.com/show_bug.cgi?id=52348#c6

Therefore I'm closing this issue.

**Closed by davidbritch** 2018-03-13 14:40 UTC
