### ISSUE TITLE
Sample WorkingWithImages seems not to be working

### ISSUE THREAD

**Issue by Hiilbig** [xamarin/xamarin-forms-samples#90] opened 2016-03-29 00:57 UTC
I am trying to compile and run Xamarin sample WorkingWithImages but it keep crashing in the iOS simulator without any error messages in the console.

I am using the latest version of Xamarin Studio on a Mac

**Comment by Rajneesh360Logica** [comment] 2016-06-28 17:49
Hi @Hiilbig I have checked this issue but not able to reproduce it. I am successfully able to build and run xamarin-forms "WorkingWithImages" sample successfully.

Screencast: http://www.screencast.com/t/bsPTqYaYBu

This issue issue seems fixed to me, hence I am closing this issue. If you still face this issue so feel free to reopen it also if possible please provide build/sample info.

Thanks..!

**Closed** 2016-06-28 18:30 UTC
