### ISSUE TITLE
Java.Lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.xamarin.deeplinking. Make sure to call FirebaseApp.initializeApp(Context) first.

### ISSUE THREAD

**Issue by pmahend1** [xamarin/xamarin-forms-samples#367] opened 2018-09-10 17:45 UTC
###Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/DeepLinking

### Description

1) Java.Lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.xamarin.deeplinking. Make sure to call FirebaseApp.initializeApp(Context) first.

Even after adding ` FirebaseApp.InitializeApp(this);` still gives error

2) Even the `ToolbarItems` is not visible on Android. Code for the same is ..
```

<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="DeepLinking.TodoListPage"
             Title="Todo">
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="+"
                     Clicked="OnAddItemClicked"
                     Icon="plus.png">
            <ToolbarItem.Icon>
                <OnPlatform x:TypeArguments="FileImageSource">
                    <On Platform="Android"
                        Value="plus.png" />
                </OnPlatform>
            </ToolbarItem.Icon>
```

### Steps to Reproduce

1. Open Deeplinking project in Visual studio
2. Compile and run
3. Add new ToDoItem

### Expected Behavior
1) Should not throw error
Please add a default firebase options. Since its a sample all users should not need to get firebase registration.

2) ToolbarItems to be displayed. Otherwise update code to not use toolbaritems and add simple button or Image with tap action 

### Actual Behavior
App crashes

### Information
```


Java.Lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.xamarin.deeplinking. Make sure to call FirebaseApp.initializeApp(Context) first.
```

- IDE and IDE version:  **Visual Studio 2017 v15.8.3** 
- Platform with the issue: 
  - iOS:  NA
  - Android: Xamarin.Android SDK   9.0.0.19 (HEAD/a8a3b0ec7)
  - UWP:  NA
- Device or simulator/emulator: both

**Comment by conceptdev** [comment] 2018-10-19 01:45
Hey @pmahend1 is this a duplicate of https://github.com/xamarin/xamarin-forms-samples/issues/368 or do you consider them to be separate issues?

**Comment by pmahend1** [comment] 2018-10-19 02:01
@conceptdev it's slightly different but the PR should fix this issue too. I think you can close both once deeplinking project sample has been fixed.

**Comment by davidbritch** [comment] 2018-11-28 13:45
Sample updated.

**Closed by davidbritch** 2018-11-28 13:45 UTC
Labels: android
