### ISSUE TITLE
Adding a sixth ShellContent item results in unexpected behaviour

### ISSUE THREAD

**Issue by DaveBrickley** [xamarin/xamarin-forms-samples#634] opened 2020-07-01 09:41 UTC
### Sample

Xaminals sample

### Description

When the number of ShellContent elements inside FlyoutItem exceeds five, unexpected behaviour occurs

### Steps to Reproduce

1. Edit the Xaminals AppShell xaml file to include a sixth ShellContent item
2. Run the code
3. Click the first five links - all is normal
4. Click the sixth and instead of the target window being replaced, a vanilla white list view is shown with 'More' in the heading, and there is no way to return to the Shell view
5. Please note that even though I am reusing an existing ShellContent item (changing only the route name to avoid an 'ambiguous reference' error), I first spotted this in my own project, with a ShellContent item that was entirely unique - I only did the minimum required to edit the 'example' project to satisfy myself the outcome was the same, i.e. it's not just happening because the items have elements in common

![Screenshot 2020-07-01 at 10 39 54](https://user-images.githubusercontent.com/45126043/86229172-3e64e480-bb87-11ea-9fc9-bab334ec59bb.png)

### Expected Behavior

There is no documented limit on the number of ShellContent items so I'd expect them all to work the same

### Actual Behavior

User is taken to a page from which they can't return

### Information

- IDE and IDE version: Visual Studio Mac 8.6.4
- Platform with the issue: 
  - iOS:  
- Device or simulator/emulator: Emulator

**Comment by DaveBrickley** [comment] 2020-07-01 12:02
@jamesmontemagno sorry to bother you James, would you be able to advise on this please?

**Comment by jamesmontemagno** [comment] 2020-07-01 22:29
That is the expected behavior. You can only have 5 tabs on iOS per design and how the control works.

**Comment by DaveBrickley** [comment] 2020-07-02 10:54
@jamesmontemagno OK this presents me with a problem which I can demonstrate using the Xaminals code

- You have five items inside FlyoutMenu and three outside
- Select monkeys. Click four or five monkeys, just to build up the Navigation stack
- Now click About
- Now click Monkeys again. Instead of seeing the Index page of monkeys, you have to browse back through the four or five you picked before you get to the index page again
- HOWEVER, on selecting Monkeys the second time, having been to About, NavigationsStack is 1, meaning you cannot simply do a PopToRoot to look for this outcome

This behaviour does NOT occur if every item is inside FlyoutMenu, but I need to have more than five menu options, so it's unavoidable

I know you didn't write the Forms code, but it's a bit of a blocker!

**Comment by jamesmontemagno** [comment] 2020-07-06 17:27
I would post an issue with a reproduction in http://github.com/xamarin/xamarin.forms as the team looks at all of them there. 

I think what you described is correct behavior as far as it keeping the navigation stack as you can pop back manually if you desire. But I would write it up in the xamarin.forms github so they can look

**Comment by DaveBrickley** [comment] 2020-07-06 17:30
@jamesmontemagno It doesn’t keep the stack tho - it counts it as 1 even tho the user has a list of pages to ‘back’ through 

I Have tagged the issue with a supporting video onto an existing bug report

**Comment by davidbritch** [comment] 2020-08-18 11:18
Looks like this is being taken care of in the engineering repo, so I'll close the issue here.

**Closed by davidbritch** 2020-08-18 11:18 UTC
