### ISSUE TITLE
Map sample does not work

### ISSUE THREAD

**Issue by duzenko** [xamarin/xamarin-forms-samples#252] opened 2017-12-14 15:59 UTC
Using the latest VS2017.
The map control shows up blank.
![screenshot_20171214-175809](https://user-images.githubusercontent.com/1481807/34001365-73a48dce-e0f8-11e7-91c2-f10e20112862.png)

**Comment by MuriloViviani** [comment] 2017-12-22 12:34
Hey @duzenko 

This problem may be related to your Google Map API Key!
Check if your key is active or if it is not blocked to a single _SHA application Fingerprint_

If your key is enabled and it is not blocked to a _SHA Fingerprint_, check if your key is set in your application Manifest's `meta-data android:name="com.google.android.maps.v2.API_KEY"` tag, and if all of the permissions needed by the map are set, like the internet permission and the locations permissions (if needed)

**Comment by duzenko** [comment] 2017-12-23 07:45
That worked

**Comment by MuriloViviani** [comment] 2017-12-23 17:56
yey! Just close this issue now that the problem is solved!

**Comment by MuriloViviani** [comment] 2017-12-29 11:32
Hey! So how are we about this Issue?
Is there any other thing regarding this topic?

**Closed** 2017-12-29 20:15 UTC
