### ISSUE TITLE
The custom pin image for CustomRenderer.iOS does not work in the latest iOS

### ISSUE THREAD

**Issue by jsenich** [xamarin/xamarin-forms-samples#107] opened 2016-06-09 17:44 UTC
The default pin image is not replaced with the custom one defined in CustomRenderer.iOS.CustomMapRenderer when using iOS 9.3.

**Comment by Rajneesh360Logica** [comment] 2016-06-28 18:25
Hi @jsenich 
Thanks for reporting this issue. I have checked this issue but I am not able to reproduce this issue. Please refer the screencast: http://www.screencast.com/t/eAg8z8m9

Could you please have a look into it, and if possible please attach complete build/sample info. That would be very helpful to reproduce this issue at our end.

Thanks..!

**Comment by jsenich** [comment] 2016-06-28 21:12
Hi @Rajneesh360Logica,
Thanks for the response. The issue that I'm running into isn't with the annotation view, pop up but with the pin image itself. The pin image that is being displayed seems to be the default red iOS pin rather than the custom purple pin.png that is being set in the example code. My current environment is VS 2015 Update 3 with Xamarin 4.1.1.3 and my mac environment info is here: 
[mac_xamarin_info.txt](https://github.com/xamarin/xamarin-forms-samples/files/338067/mac_xamarin_info.txt)

Below are the screenshots of the map in iOS 8.4 vs iOS 9.3. 


![map-ios84](https://cloud.githubusercontent.com/assets/1821282/16432102/a55f7064-3d51-11e6-8b1e-e954ada1b9ec.png)
![map-ios93](https://cloud.githubusercontent.com/assets/1821282/16432101/a55eccb8-3d51-11e6-9d77-e9ebfae545fc.png)

**Comment by DeadL1nk** [comment] 2016-07-26 08:55
I have exactly the same problem. 
My environment : Xamarin Studio 6.0.1 and IOS 9.3.

**Comment by davidbritch** [comment] 2016-08-09 17:55
Fixed in master. Replaced MKPinAnnotationView with MKAnnotationView.

**Closed by davidbritch** 2016-08-09 17:55 UTC
